version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENVIRONMENT: ${APP_ENV}
    command: [
      "./wait-for-it.sh",
      "espresso-db:3306", 
      "--", 
      "uwsgi", 
      "--log-5xx", 
      "--disable-logging", 
      "--logto=uwsgi.log", 
      "--ini=uwsgi.ini"
      ]
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./app/core/databases/mysql-data:/var/lib/mysql
    env_file:
      - .env
  
  api-dev:
    container_name: espresso-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        project: "espresso"
      args:
        ENVIRONMENT: ${APP_ENV}
    command: [
      "./wait-for-it.sh",
       "database-dev:3306",
      "--",
      "uwsgi",
      "--py-autoreload=1",
      "--ini=uwsgi.ini"
      ] 
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - espresso-db
  
  # espresso-install:
  #   container_name: espresso-dev
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       ENVIRONMENT: ${APP_ENV}
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: pip install -r requirements.txt -t /app/lib

  espresso-db:
    container_name: database-dev
    image: mariadb:latest
    build:
      context: .
      labels:
        project: "espresso"
    ports:
      - 3306:3306
    volumes:
      - ./app/core/databases/mysql-data:/var/lib/mysql
    env_file:
      - .env