version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        project: "espresso"
      args:
        ENVIRONMENT: ${APP_ENV}
    command: [
      "./wait-for-it.sh",
      "db-espresso:3306", 
      "--", 
      "uwsgi", 
      "--log-5xx", 
      "--disable-logging", 
      "--logto=uwsgi.log", 
      "--ini=uwsgi.ini"
      ]
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db-espresso

  db-espresso:
    image: mariadb:latest
    labels:
      project: "espresso"
    ports:
      - 3306:3306
    volumes:
      - ./app/core/databases/mysql-data:/var/lib/mysql
    env_file:
      - .env
  
  api-dev:
    container_name: espresso-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENVIRONMENT: ${APP_ENV}
    labels:
      project: "espresso"
    command: [
      "./wait-for-it.sh",
       "db-espresso-dev:3306",
      "--",
      "uwsgi",
      "--py-autoreload=1",
      "--ini=uwsgi.ini"
      ] 
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db-espresso-dev

  db-espresso-dev:
    image: mariadb:latest  
    labels:
      project: "espresso"
    ports:
      - 3306:3306
    volumes:
      - ./app/core/databases/mysql-data:/var/lib/mysql
    env_file:
      - .env