version: "3"

services:
  espresso_api:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - .:/flask
    working_dir: /flask
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./app/core/databases/mysql-data:/var/lib/mysql
    env_file:
      - .env
